import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import { Main } from "../components/main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Parkway Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
      </main>
    </>
  );
}
